kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go version
  - go get ./...
  - go build ./...
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
  - golangci-lint run --enable dupl --enable goconst --enable gocritic --enable misspell --enable prealloc --enable unconvert --enable unparam --enable gochecknoinits
  - go test -v -race -coverprofile=coverage.txt ./...

- name: coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov-token
    files:
      - coverage.txt
