pipeline:
  testing:
    image: golang
    environment:
      GO111MODULES: on
    commands:
      - go version
      - go build -v
      - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - golangci-lint run
      - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - bash <(curl -s https://codecov.io/bash)