kind: pipeline
name: default

steps:
- name: test
  image: golang
  environment:
    GO111MODULE: on
  commands:
  - go version
  - go get ./...
  - go build ./...
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
  - golangci-lint run
  - go test -v -race -coverprofile=coverage.txt ./...

- name: coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov-token
    files:
      - coverage.txt

- name: discord
  image: appleboy/drone-discord
  when:
    status:
    - failure
  settings:
    webhook_id:
      from_secret: discord-id
    webhook_token:
      from_secret: discord-token